/**
 * Maps team names (as returned by football-data.org) to ISO 3166-1 alpha-2
 * country codes used by flagcdn.com.
 */
const FLAG_CODES: Record<string, string> = {
  // South America
  Argentina: 'ar',
  Brazil: 'br',
  Colombia: 'co',
  Ecuador: 'ec',
  Uruguay: 'uy',
  Chile: 'cl',
  Venezuela: 've',
  Paraguay: 'py',
  Bolivia: 'bo',
  Peru: 'pe',

  // Europe
  France: 'fr',
  England: 'gb-eng',
  Germany: 'de',
  Spain: 'es',
  Portugal: 'pt',
  Netherlands: 'nl',
  Belgium: 'be',
  Italy: 'it',
  Croatia: 'hr',
  Switzerland: 'ch',
  Denmark: 'dk',
  Austria: 'at',
  Poland: 'pl',
  Serbia: 'rs',
  'Türkiye': 'tr',
  Turkey: 'tr',
  Hungary: 'hu',
  Scotland: 'gb-sct',
  Romania: 'ro',
  Ukraine: 'ua',
  Slovenia: 'si',
  Slovakia: 'sk',
  'Czech Republic': 'cz',
  Czechia: 'cz',
  Albania: 'al',
  Georgia: 'ge',
  Greece: 'gr',
  Sweden: 'se',
  Norway: 'no',
  Finland: 'fi',
  Iceland: 'is',
  'North Macedonia': 'mk',
  Montenegro: 'me',
  Kosovo: 'xk',
  Bosnia: 'ba',
  'Bosnia and Herzegovina': 'ba',
  'Bosnia-Herzegovina': 'ba',
  Wales: 'gb-wls',
  Luxembourg: 'lu',
  Malta: 'mt',

  // CONCACAF
  'United States': 'us',
  USA: 'us',
  Mexico: 'mx',
  Canada: 'ca',
  Panama: 'pa',
  Honduras: 'hn',
  'Costa Rica': 'cr',
  Jamaica: 'jm',
  'Trinidad and Tobago': 'tt',
  Guatemala: 'gt',
  'El Salvador': 'sv',
  Haiti: 'ht',
  Cuba: 'cu',

  // Africa
  Morocco: 'ma',
  Senegal: 'sn',
  Nigeria: 'ng',
  Egypt: 'eg',
  Cameroon: 'cm',
  "Côte d'Ivoire": 'ci',
  'Ivory Coast': 'ci',
  Mali: 'ml',
  Algeria: 'dz',
  'South Africa': 'za',
  Tunisia: 'tn',
  Ghana: 'gh',
  'DR Congo': 'cd',
  Zambia: 'zm',
  Uganda: 'ug',
  Tanzania: 'tz',
  Ethiopia: 'et',
  Angola: 'ao',
  Mozambique: 'mz',
  Zimbabwe: 'zw',
  Burkina: 'bf',
  'Burkina Faso': 'bf',
  Guinea: 'gn',
  Kenya: 'ke',
  Rwanda: 'rw',

  // Asia
  Japan: 'jp',
  'South Korea': 'kr',
  'Korea Republic': 'kr',
  'Saudi Arabia': 'sa',
  Australia: 'au',
  Iran: 'ir',
  Iraq: 'iq',
  Jordan: 'jo',
  Uzbekistan: 'uz',
  Qatar: 'qa',
  UAE: 'ae',
  'United Arab Emirates': 'ae',
  China: 'cn',
  India: 'in',
  Thailand: 'th',
  Vietnam: 'vn',
  Philippines: 'ph',
  Indonesia: 'id',
  Malaysia: 'my',
  Oman: 'om',
  Bahrain: 'bh',
  Kuwait: 'kw',
  Kyrgyzstan: 'kg',
  Tajikistan: 'tj',
  Palestine: 'ps',
  Syria: 'sy',
  Lebanon: 'lb',
  'North Korea': 'kp',
  Myanmar: 'mm',
  Mongolia: 'mn',
  Afghanistan: 'af',
  Pakistan: 'pk',
  Bangladesh: 'bd',
  Nepal: 'np',

  // OFC
  'New Zealand': 'nz',
  Fiji: 'fj',
  'Papua New Guinea': 'pg',
  Vanuatu: 'vu',
  Tahiti: 'pf',
  'Solomon Islands': 'sb',
};

export function flagUrl(teamName: string): string {
  const code = FLAG_CODES[teamName];
  if (!code) return '';
  return `https://flagcdn.com/w80/${code}.png`;
}
